#!/bin/sh
if [ -z "$1" ]; then
    echo "usage: export BLOCK1 [BLOCK2]" >&2
    exit 1
fi
b="$1"
if [ -z "$2" ]; then
    e=$(expr "$1" + 1)
else
    e=$(expr "$2" + 1)
fi
while [ "$b" != "$e" ]; do
    awk '
function trim(s) {
    p = match(s, "[ \n\t]+$")
    if(p != 0) return substr(s, 1, RSTART)
    return s
}
{
    s = $0
    while(s != "") {
        ln = trim(substr(s, 1, 64))
        s = substr(s, 65)
        printf("%s\n", ln)
    }
}' < $b
    b=$(expr $b + 1)
done
